url: https://alfieindesigns.github.io
baseurl: ""

# Site settings
title: alfieindesigns
email: alfiellon@gmail.com
description: "alfieindesigns - Lead Shopify Developer / Senior Front-End Developer"

# Team names, titles and social links
people:
- name: Alfie Nollora
  pic: 1
  position: Lead Shopify Developer / Senior Front-End Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Alfie Nollora
  pic: 2
  position: Lead Shopify Developer / Senior Front-End Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: Alfie Nollora
  pic: 3
  position: Lead Shopify Developer / Senior Front-End Developer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://x.com/alfieindesigns
  - title: facebook
    url: https://www.facebook.com/alfieindesigns
  - title: github
    url: https://github.com/alfieindesigns

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty